### ISSUE TITLE
Xenia 3.2.2018. started crashing at some games

### ISSUE THREAD

**Issue by zemzema** [benvanik/xenia#1092]
This is the log for Castlevania: Lords of Shadow 2, it was in state-menu, till last version, emulator crash before menus. 

Here is the log, maybe you can get something from it.

[xenia.zip](https://github.com/benvanik/xenia/files/1775680/xenia.zip)

**Comment by DrChat** [comment]
Grab HWInfo64 and post a screenshot of your CPU Features. If you don't know where that is, just post a screenshot of the system summary dialog.

**Comment by zemzema** [comment]
![sysinfo](https://user-images.githubusercontent.com/33085810/36913098-1f7eccf8-1e49-11e8-8633-935210cad732.png)

**Comment by SakataGintokiYT** [comment]
@DrChat 
**[0577b6c9]**-This commit caused a crash in Dragon Ball: Raging Blast 2-Demo
**Log:** [xenia.log](https://github.com/benvanik/xenia/files/1777370/xenia.log)

![1](https://user-images.githubusercontent.com/13681488/36933216-8890d1e6-1ed5-11e8-8873-50dba94e40f6.png)
![2](https://user-images.githubusercontent.com/13681488/36933217-89d3fa6a-1ed5-11e8-8232-689e4d05ffc7.png)

**Comment by DrChat** [comment]
@SakataGintokiYT You sure it's that specific commit? It fixes what was a broken instruction (negative inputs should be clamped to 0)

**Comment by zemzema** [comment]
I have a different crash.

![crash](https://user-images.githubusercontent.com/33085810/36936417-7b700628-1f05-11e8-811e-5be5b35dd186.png)

**Comment by SakataGintokiYT** [comment]
@DrChat 
I don't know, which changes has broken this game but crashing began with this build:  https://ci.appveyor.com/project/benvanik/xenia/build/1.0.1198-master/job/uvrqij7r32xqgoru/artifacts

**Comment by DrChat** [comment]
Okay, it's related to the `VECTOR_CONVERT_F2I` class of instructions (`vtc[s/u]xs`).
Rather, these instructions were previously broken which masked an underlying issue.

**Comment by SakataGintokiYT** [comment]
@DrChat 
Dragon Ball: Raging Blast 2-Demo still crashes.
You can reproduce the issue too in Bomberman Live.
![bez tytulu](https://user-images.githubusercontent.com/13681488/36939287-a11d7062-1f2e-11e8-8b77-32d9c7ad595a.png)
Log:
[xenia.log](https://github.com/benvanik/xenia/files/1777894/xenia.log)

**Comment by zemzema** [comment]
When I better look, Xenia error in windows log have:
Faulting module path: C:\WINDOWS\System32\amdvlk64.dll
But in system32 should not have 64 bit version of driver placed there, also I reinstalled AMD GPU drivers, but I cannot find amdvlk64.dll.

**Comment by simontoft** [comment]
@zemzema - System32 is for 64bit dlls (on 64 bit systems), SysWoW64 is for 32 bit dlls. And no, it's not logical.

**Comment by DrChat** [comment]
Okay, confirm that 157c7780af7bbe9061a0a44d720622270b8838df fixes your issues and I will close this issue.

**Comment by SakataGintokiYT** [comment]
Crashes is fixed now.

**Comment by DrChat** [comment]
Awesome!

**Comment by zemzema** [comment]
On my computer problem still exist.

Faulting application name: xenia.exe, version: 0.0.0.0, time stamp: 0x5a9b4bfd
Faulting module name: amdvlk64.dll, version: 9.2.10.18, time stamp: 0x5aac6393
Exception code: 0xc0000005
Fault offset: 0x0000000000098900
Faulting process ID: 0x2bc4
Faulting application start time: 0x01d3c43932349d5d
Faulting application path: I:\Games\Xenia\xenia.exe
Faulting module path: C:\WINDOWS\System32\amdvlk64.dll
Report ID: 6ade4fbb-b5dd-4a95-90cb-0f784a1ab103
Faulting package full name: 
Faulting package-relative application ID:

**Comment by indiedriver** [comment]
@zemzema More likely related to #756
