### ISSUE TITLE
OpenGL 4.5 Black Screen on AMD Cards

### ISSUE THREAD

**Issue by thx3ever** [benvanik/xenia#563]
Can it be fixed? When running any game  with latest opengl 4.5 Context and shading language 4.5 amd driver released 9 march, hopefully it can be fixed for amd radeon users

**Comment by Razzile** [comment]
this is the wrong place for issues related to specific games. please report your issue here https://github.com/xenia-project/game-compatibility/issues/206

**Comment by RenegadeSaiyan** [comment]
Which Build are you using?

**Comment by thx3ever** [comment]
latest and i can ear only sound no image at all

**Comment by RenegadeSaiyan** [comment]
Post a link to the build you are using

**Comment by thx3ever** [comment]
git clone https://github.com/benvanik/xenia.git --branch master 
git submodule update --init

**Comment by RenegadeSaiyan** [comment]
Can you post a download to your vulkan branch, as in a already completed one?

**Comment by thx3ever** [comment]
https://drive.google.com/drive/folders/0BwNnlaBZX4Nob3hQdlBIYlptcEk
XeniaGL build on máster
XeniaVK build on Vulkan
EDIT: My graphics card are AMD HD 7770

**Comment by RenegadeSaiyan** [comment]
Um I can't view the folder

**Comment by thx3ever** [comment]
https://drive.google.com/open?id=0BwNnlaBZX4NoeVRCQjlXeE0yMTQ
https://drive.google.com/open?id=0BwNnlaBZX4NoWTZZTHpFMW5qQU0

**Comment by RenegadeSaiyan** [comment]
Sent you a request to view the folder

**Comment by thx3ever** [comment]
OK now u have acess

**Comment by RenegadeSaiyan** [comment]
It's probably due to the fact that the vulkan build isn't ready yet, I'm going to try the GL build next

**Comment by thx3ever** [comment]
ok

**Comment by RenegadeSaiyan** [comment]
Well you should probably wait until the vulkan build is ready then try it.

**Comment by thx3ever** [comment]
ok

**Comment by thx3ever** [comment]
Maybe this information are usable

G> 00000004 Generated vertex shader at 0x000000021FCA6014 (96b):
/*    0.0 */       exec 
/*    3   */          nop
/*    0.1 */       alloc interpolators
/*    1.0 */       exec 
/*    4   */          max o0._, r0, r0
/*    1.1 */       alloc position
/*    2.0 */       exec 
/*    5   */          max oPos.0001, r1, r1
/*    2.1 */       exece 
/*    6   */          nop
!> 00000004 Pixel shader invalid
!> 00000004 Unable to prepare draw shaders
!> 00000004 **** INDIRECT RINGBUFFER: Failed to execute packet.

**Comment by sephiroth99** [comment]
PR #562 is needed for xenia to work again with the latest AMD drivers, right now the shaders fail to compile.

But even with that fixed, most game are showing a black screen only with AMD anyway...

**Comment by DrChat** [comment]
I believe this issue is a duplicate, but regardless this should be fixed in the Vulkan branch later.

**Comment by thx3ever** [comment]
My card AMD HD7770 are vulkan ready but don't support alphatoone, im going to buy NVIDIA

**Comment by Gamedev1909** [comment]
This issues was fixed 3 days ago http://www.emucr.com/2016/03/xenia-git-20160222.html now no issues on the amd side full opengl 4.5 godness

**Comment by lukestrong** [comment]
Issue is still present with banjo kazooie and tooie (the only games I've tested)
Something interesting though is that in banjo tooie, is if I stand still for a moment and then walk, it will show a small glimpse of video for about a second then disappear again.
Also if I go into the water in the opening level, it will show this: [http://imgur.com/GRcZKYk](http://imgur.com/GRcZKYk)
Hope that helps somebody with this :)

**Comment by Razzile** [comment]
that sounds like more of a problem with the game than AMD cards. I remember my GTX 770 could only render half of the level on banjo kazooie

**Comment by lukestrong** [comment]
I'm not sure because there are quite a few videos of these games working in xenia.
here's a couple of the latest videos of xenia running these games.
banjo kazooie: https://www.youtube.com/watch?v=uJ6GP2A3x0I
banjo tooie: https://www.youtube.com/watch?v=6kijZ_7ii4s
kazooie seems to run nearly-flawlessly and tooie has/had a few graphical bugs (might be fixed now, idk).

**Comment by Gamedev1909** [comment]
i guess we hope to god we get another update this year or next

**Comment by GamingDamned** [comment]
Any fixes or updates to fix this issue? I got this issue on my amd cards.

**Comment by mcdgray129** [comment]
Same issue as others. Only blackscreen and sound.
My card is an AMD R9-280x. and im using the latest build from emucr.

**Comment by ikki84** [comment]
Same issue here, Radeon R7 200, lastest amd driver installed 06/06/2016.
It seems to happen when rendering 3d objects on AMD video cards.
Mortal Kombat vs DC universe doesn´t show the characters, only the (images) probably png in the select character screen, also minecraft doesn´t show the 3d objects....
Please, there is a way to fix it?

**Comment by ikki84** [comment]
![xenia](https://cloud.githubusercontent.com/assets/16824659/16213778/695681a4-3728-11e6-890d-72c8fc19c5a7.jpg)

**Comment by mcdgray129** [comment]
Checked the latest build dated 13-07-2016 and this issue is still there. Please can anyone point me to a custom build or something that has this issue fixed for AMD users?.

**Comment by SakataGintokiYT** [comment]
Tested on [AMD HD 7850]
https://www.youtube.com/watch?v=Jo1M11JkCZs

**Comment by GamingDamned** [comment]
Still same black issue.

**Comment by fjay69** [comment]
Hello! RX 470, driver 16.12.2, Xenia 29.01.2017
Running Scott Piligrim - black screen.
'--gpu=vulkan' key causes crash.

**Comment by Razzile** [comment]
that flag shouldn't make any difference anymore as vulkan is the default renderer

**Comment by DrChat** [comment]
This is fixed in the Vulkan backend, but will not be fixed in the deprecated GL backend.
